// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Quiz1.Data;

#nullable disable

namespace Quiz1.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260917072528_v3")]
    partial class v3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Quiz1.Models.Classroom", b =>
                {
                    b.Property<int>("ClassroomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClassroomId"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<int>("Grade")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ClassroomId");

                    b.ToTable("Classrooms");

                    b.HasData(
                        new
                        {
                            ClassroomId = 1,
                            Capacity = 30,
                            Grade = 1,
                            Name = "Grade 1 - A"
                        },
                        new
                        {
                            ClassroomId = 2,
                            Capacity = 30,
                            Grade = 2,
                            Name = "Grade 2 - A"
                        },
                        new
                        {
                            ClassroomId = 3,
                            Capacity = 35,
                            Grade = 3,
                            Name = "Grade 3 - A"
                        },
                        new
                        {
                            ClassroomId = 4,
                            Capacity = 35,
                            Grade = 4,
                            Name = "Grade 4 - A"
                        },
                        new
                        {
                            ClassroomId = 5,
                            Capacity = 40,
                            Grade = 5,
                            Name = "Grade 5 - A"
                        },
                        new
                        {
                            ClassroomId = 6,
                            Capacity = 40,
                            Grade = 6,
                            Name = "Grade 6 - A"
                        });
                });

            modelBuilder.Entity("Quiz1.Models.Department", b =>
                {
                    b.Property<int>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepartmentId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DepartmentId");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            DepartmentId = 1,
                            Description = "Department of Mathematics",
                            Name = "Mathematics"
                        },
                        new
                        {
                            DepartmentId = 2,
                            Description = "Department of Science",
                            Name = "Science"
                        },
                        new
                        {
                            DepartmentId = 3,
                            Description = "Department of English Language",
                            Name = "English"
                        },
                        new
                        {
                            DepartmentId = 4,
                            Description = "Department of Arabic Language",
                            Name = "Arabic"
                        },
                        new
                        {
                            DepartmentId = 5,
                            Description = "Department of Computer Science",
                            Name = "Computer Science"
                        });
                });

            modelBuilder.Entity("Quiz1.Models.Enrollment", b =>
                {
                    b.Property<int>("EnrollmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EnrollmentId"));

                    b.Property<DateTime>("EnrollmentDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Grade")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("SubjecttId")
                        .HasColumnType("int");

                    b.HasKey("EnrollmentId");

                    b.HasIndex("SubjecttId");

                    b.HasIndex("StudentId", "SubjecttId")
                        .IsUnique();

                    b.ToTable("Enrollments");

                    b.HasData(
                        new
                        {
                            EnrollmentId = 1,
                            EnrollmentDate = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Grade = 85m,
                            StudentId = 1,
                            SubjecttId = 1
                        },
                        new
                        {
                            EnrollmentId = 2,
                            EnrollmentDate = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Grade = 90m,
                            StudentId = 2,
                            SubjecttId = 1
                        },
                        new
                        {
                            EnrollmentId = 3,
                            EnrollmentDate = new DateTime(2025, 9, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Grade = 88m,
                            StudentId = 3,
                            SubjecttId = 2
                        },
                        new
                        {
                            EnrollmentId = 4,
                            EnrollmentDate = new DateTime(2025, 9, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Grade = 76m,
                            StudentId = 4,
                            SubjecttId = 2
                        },
                        new
                        {
                            EnrollmentId = 5,
                            EnrollmentDate = new DateTime(2025, 9, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Grade = 92m,
                            StudentId = 5,
                            SubjecttId = 3
                        },
                        new
                        {
                            EnrollmentId = 6,
                            EnrollmentDate = new DateTime(2025, 9, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Grade = 87m,
                            StudentId = 6,
                            SubjecttId = 3
                        },
                        new
                        {
                            EnrollmentId = 7,
                            EnrollmentDate = new DateTime(2025, 9, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Grade = 95m,
                            StudentId = 7,
                            SubjecttId = 4
                        },
                        new
                        {
                            EnrollmentId = 8,
                            EnrollmentDate = new DateTime(2025, 9, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Grade = 89m,
                            StudentId = 8,
                            SubjecttId = 4
                        },
                        new
                        {
                            EnrollmentId = 9,
                            EnrollmentDate = new DateTime(2025, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Grade = 91m,
                            StudentId = 9,
                            SubjecttId = 5
                        },
                        new
                        {
                            EnrollmentId = 10,
                            EnrollmentDate = new DateTime(2025, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Grade = 94m,
                            StudentId = 10,
                            SubjecttId = 5
                        });
                });

            modelBuilder.Entity("Quiz1.Models.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentId"));

                    b.Property<int>("ClassroomId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("DOF")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("StudentId");

                    b.HasIndex("ClassroomId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            StudentId = 1,
                            ClassroomId = 1,
                            DOF = new DateOnly(2018, 3, 15),
                            Email = "ali.hassan@student.com",
                            Firstname = "Ali",
                            Lastname = "Hassan",
                            Phone = "01112345678"
                        },
                        new
                        {
                            StudentId = 2,
                            ClassroomId = 1,
                            DOF = new DateOnly(2018, 7, 20),
                            Email = "omar.ahmed@student.com",
                            Firstname = "Omar",
                            Lastname = "Ahmed",
                            Phone = "01123456789"
                        },
                        new
                        {
                            StudentId = 3,
                            ClassroomId = 2,
                            DOF = new DateOnly(2017, 5, 10),
                            Email = "youssef.mohamed@student.com",
                            Firstname = "Youssef",
                            Lastname = "Mohamed",
                            Phone = "01134567890"
                        },
                        new
                        {
                            StudentId = 4,
                            ClassroomId = 2,
                            DOF = new DateOnly(2017, 9, 25),
                            Email = "adam.mahmoud@student.com",
                            Firstname = "Adam",
                            Lastname = "Mahmoud",
                            Phone = "01145678901"
                        },
                        new
                        {
                            StudentId = 5,
                            ClassroomId = 3,
                            DOF = new DateOnly(2016, 2, 5),
                            Email = "mariam.ali@student.com",
                            Firstname = "Mariam",
                            Lastname = "Ali",
                            Phone = "01156789012"
                        },
                        new
                        {
                            StudentId = 6,
                            ClassroomId = 3,
                            DOF = new DateOnly(2016, 11, 12),
                            Email = "nour.ibrahim@student.com",
                            Firstname = "Nour",
                            Lastname = "Ibrahim",
                            Phone = "01167890123"
                        },
                        new
                        {
                            StudentId = 7,
                            ClassroomId = 4,
                            DOF = new DateOnly(2015, 6, 18),
                            Email = "khaled.sayed@student.com",
                            Firstname = "Khaled",
                            Lastname = "Sayed",
                            Phone = "01178901234"
                        },
                        new
                        {
                            StudentId = 8,
                            ClassroomId = 4,
                            DOF = new DateOnly(2015, 10, 8),
                            Email = "salma.hassan@student.com",
                            Firstname = "Salma",
                            Lastname = "Hassan",
                            Phone = "01189012345"
                        },
                        new
                        {
                            StudentId = 9,
                            ClassroomId = 5,
                            DOF = new DateOnly(2014, 4, 22),
                            Email = "ziad.mostafa@student.com",
                            Firstname = "Ziad",
                            Lastname = "Mostafa",
                            Phone = "01190123456"
                        },
                        new
                        {
                            StudentId = 10,
                            ClassroomId = 5,
                            DOF = new DateOnly(2014, 12, 3),
                            Email = "lina.adel@student.com",
                            Firstname = "Lina",
                            Lastname = "Adel",
                            Phone = "01101234567"
                        });
                });

            modelBuilder.Entity("Quiz1.Models.Subject", b =>
                {
                    b.Property<int>("SubjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubjectId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Grade")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TeacherId")
                        .HasColumnType("int");

                    b.HasKey("SubjectId");

                    b.HasIndex("TeacherId");

                    b.ToTable("Subjects");

                    b.HasData(
                        new
                        {
                            SubjectId = 1,
                            Description = "Basic mathematics and problem solving",
                            Grade = "45",
                            Name = "Mathematics",
                            TeacherId = 1
                        },
                        new
                        {
                            SubjectId = 2,
                            Description = "Advanced mathematical concepts",
                            Grade = "45",
                            Name = "Advanced Mathematics",
                            TeacherId = 2
                        },
                        new
                        {
                            SubjectId = 3,
                            Description = "Basic science and natural phenomena",
                            Grade = "45",
                            Name = "Science",
                            TeacherId = 3
                        },
                        new
                        {
                            SubjectId = 4,
                            Description = "English grammar, reading and writing",
                            Grade = "56",
                            Name = "English Language",
                            TeacherId = 4
                        },
                        new
                        {
                            SubjectId = 5,
                            Description = "Arabic grammar, reading and writing",
                            Grade = "80",
                            Name = "Arabic Language",
                            TeacherId = 5
                        },
                        new
                        {
                            SubjectId = 6,
                            Description = "Programming and computer science fundamentals",
                            Grade = "70",
                            Name = "Computer Science",
                            TeacherId = 6
                        });
                });

            modelBuilder.Entity("Quiz1.Models.Teacher", b =>
                {
                    b.Property<int>("TeacherId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TeacherId"));

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("TeacherId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("EmailAddress")
                        .IsUnique();

                    b.ToTable("Teachers");

                    b.HasData(
                        new
                        {
                            TeacherId = 1,
                            DepartmentId = 1,
                            EmailAddress = "ahmed.hassan@school.com",
                            FirstName = "Ahmed",
                            LastName = "Hassan",
                            Phone = "01012345678",
                            Salary = 15000m
                        },
                        new
                        {
                            TeacherId = 2,
                            DepartmentId = 1,
                            EmailAddress = "mohamed.ali@school.com",
                            FirstName = "Mohamed",
                            LastName = "Ali",
                            Phone = "01023456789",
                            Salary = 14500m
                        },
                        new
                        {
                            TeacherId = 3,
                            DepartmentId = 2,
                            EmailAddress = "sara.ibrahim@school.com",
                            FirstName = "Sara",
                            LastName = "Ibrahim",
                            Phone = "01034567890",
                            Salary = 15500m
                        },
                        new
                        {
                            TeacherId = 4,
                            DepartmentId = 3,
                            EmailAddress = "omar.mahmoud@school.com",
                            FirstName = "Omar",
                            LastName = "Mahmoud",
                            Phone = "01045678901",
                            Salary = 15000m
                        },
                        new
                        {
                            TeacherId = 5,
                            DepartmentId = 4,
                            EmailAddress = "mariam.ahmed@school.com",
                            FirstName = "Mariam",
                            LastName = "Ahmed",
                            Phone = "01056789012",
                            Salary = 16000m
                        },
                        new
                        {
                            TeacherId = 6,
                            DepartmentId = 5,
                            EmailAddress = "youssef.khaled@school.com",
                            FirstName = "Youssef",
                            LastName = "Khaled",
                            Phone = "01067890123",
                            Salary = 17000m
                        });
                });

            modelBuilder.Entity("Quiz1.Models.Enrollment", b =>
                {
                    b.HasOne("Quiz1.Models.Student", "Student")
                        .WithMany("Enrollments")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Quiz1.Models.Subject", "Subject")
                        .WithMany("Enrollments")
                        .HasForeignKey("SubjecttId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("Quiz1.Models.Student", b =>
                {
                    b.HasOne("Quiz1.Models.Classroom", "Classroom")
                        .WithMany("Students")
                        .HasForeignKey("ClassroomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Classroom");
                });

            modelBuilder.Entity("Quiz1.Models.Subject", b =>
                {
                    b.HasOne("Quiz1.Models.Teacher", "Teacher")
                        .WithMany("Subjects")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("Quiz1.Models.Teacher", b =>
                {
                    b.HasOne("Quiz1.Models.Department", "Department")
                        .WithMany("Teachers")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Quiz1.Models.Classroom", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("Quiz1.Models.Department", b =>
                {
                    b.Navigation("Teachers");
                });

            modelBuilder.Entity("Quiz1.Models.Student", b =>
                {
                    b.Navigation("Enrollments");
                });

            modelBuilder.Entity("Quiz1.Models.Subject", b =>
                {
                    b.Navigation("Enrollments");
                });

            modelBuilder.Entity("Quiz1.Models.Teacher", b =>
                {
                    b.Navigation("Subjects");
                });
#pragma warning restore 612, 618
        }
    }
}
